### ISSUE TITLE
能否借鉴StickySearch这款插件，可以选取需要的字词高亮？因为对中文支持不好

### ISSUE THREAD

**Issue by tortoo** [ownself/CursorWordHighlighter#1]
您的插件非常棒，但是因为sublime对中文支持不好，所以光标所在位置不能很好选择需要的词句，而StickySearch这款插件可以选择需要的字词进行高亮，但它的其他功能较弱，比如只能有一种颜色。如果能把选择字词的功能引入进来就完美了！

**Comment by ownself** [comment]
试了一下，果然中文没办法很好的区分词汇，我看一下我能做点什么嘛

**Comment by ownself** [comment]
> 您的插件非常棒，但是因为sublime对中文支持不好，所以光标所在位置不能很好选择需要的词句，而StickySearch这款插件可以选择需要的字词进行高亮，但它的其他功能较弱，比如只能有一种颜色。如果能把选择字词的功能引入进来就完美了！

试了一下，果然中文没办法很好的区分词汇，我看一下我能做点什么嘛

**Comment by ownself** [comment]
> 您的插件非常棒，但是因为sublime对中文支持不好，所以光标所在位置不能很好选择需要的词句，而StickySearch这款插件可以选择需要的字词进行高亮，但它的其他功能较弱，比如只能有一种颜色。如果能把选择字词的功能引入进来就完美了！

是这样的，首先你可以在插件的Preferences里把选项"cursor_word_highlighter_whole_word"改成false，这样你颜色高亮的时候不会自动将选择范围扩大到整个"Word"，然后在SublimeText的Preferences里有一个选项"word_separators": "./\\()\"'-:,.;<>~!@#$%^&*|+=[]{}`~?",你需要将中文的逗号和句号以及其他你需要的中文标点符号加进去，这样中文的分词至少可以理解中文的标点符号。
至于按照中文逻辑来分词，恐怕这个不是SublimeText设计初衷，因为本身还是一个代码编辑器。
我想关闭"cursor_word_highlighter_whole_word"已经可以在一定程度上满足你的需要了，对吗？

**Comment by tortoo** [comment]
@ownself 我代码开发不太懂，只能提一些建议哈。中文分词已经有人做了，[这里](https://github.com/absop/ChineseTokenizer)，作者用的是jieba词库，不过他的插件是针对光标移动的，不知道能否移植过来。但这只能解决光标所在中文词的自动高亮，如果要选择短语或句子进行高亮就不行了（sublime也不能按中文标点来识别句子），我觉得[StickySearch](https://github.com/vim-zz/StickySearch)通过对光标选择的部分进行高亮，能完美解决选择任意词句进行高亮并固定显示的问题，但它又不能进行放置光标自动高亮，而且没有多种颜色显示。sublime自身包含选择并高亮相同词句的功能，虽然是临时高亮一下，也勉强能用。所以我觉得，如果能把StickySearch的选择并固定高亮的功能借鉴进来，配合CursorWordHighlighter的六种颜色，这个适用面会广一些。如果再能把中文分词做到精准框选光标所在相同词，那就完美了

**Comment by tortoo** [comment]
抱歉发出去了才收到你发的，我明白你说的，的确可以添加中文标点来让sublime学会中文断句，但还是不如随意选择进行高亮的适应面广。因为StickySearch能随意选择进行高亮，比较羡慕😹，但它不能颜色高亮，不能通过颜色区分来高亮多个选择

**Comment by ownself** [comment]
> 抱歉发出去了才收到你发的，我明白你说的，的确可以添加中文标点来让sublime学会中文断句，但还是不如随意选择进行高亮的适应面广。因为StickySearch能随意选择进行高亮，比较羡慕😹，但它不能颜色高亮，不能通过颜色区分来高亮多个选择

你把cursor_word_highlighter_whole_word改成false就可以按照自己选择进行高亮了，中文的这个分词的插件如果好用的话，很有可能可以一起工作的，你可以试试看，我也下一个试试看

**Comment by ownself** [comment]
> 抱歉发出去了才收到你发的，我明白你说的，的确可以添加中文标点来让sublime学会中文断句，但还是不如随意选择进行高亮的适应面广。因为StickySearch能随意选择进行高亮，比较羡慕😹，但它不能颜色高亮，不能通过颜色区分来高亮多个选择

似乎不行，这个情况是必须要改一下我的插件里的代码的，因为我的代码中用的是SublimeText的选词，ChineseTokenizer插件是自己写的选词函数，得调用它的才行...

**Comment by tortoo** [comment]
我测试了一下，把"cursor_word_highlighter_whole_word"改成false，可以进行选择并用颜色固定高亮，几乎做到StickySearch的功能了，好棒😹！但似乎有个bug，选择中文单字没效果，选择双字及以上都可以正常高亮。而StickySearch对单字也有效。哈，这下选择并颜色固定高亮的问题几乎解决了

**Comment by ownself** [comment]
> 我测试了一下，把"cursor_word_highlighter_whole_word"改成false，可以进行选择并用颜色固定高亮，几乎做到StickySearch的功能了，好棒😹！但似乎有个bug，选择中文单字没效果，选择双字及以上都可以正常高亮。而StickySearch对单字也有效。哈，这下选择并颜色固定高亮的问题几乎解决了

单字确实是不行的，我记得当时写的时候是有这么个技术问题的，英文也一样单个字母无法高亮，如果你能勉强够用那是最好啦，再不行的话就需要你看一下我的插件和那个中文分词插件里的代码，结合一下就可以完全做到你想要的效果，一共只有两个Python文件，几百行代码，不算太复杂。

**Comment by tortoo** [comment]
> > 我测试了一下，把"cursor_word_highlighter_whole_word"改成false，可以进行选择并用颜色固定高亮，几乎做到StickySearch的功能了，好棒😹！但似乎有个bug，选择中文单字没效果，选择双字及以上都可以正常高亮。而StickySearch对单字也有效。哈，这下选择并颜色固定高亮的问题几乎解决了
> 
> 单字确实是不行的，我记得当时写的时候是有这么个技术问题的，英文也一样单个字母无法高亮，如果你能勉强够用那是最好啦，再不行的话就需要你看一下我的插件和那个中文分词插件里的代码，结合一下就可以完全做到你想要的效果，一共只有两个Python文件，几百行代码，不算太复杂。

单字是个小问题，实际选单字的情况也极少。无奈不懂Python🙈，唉，要是那中文分词插件作者能帮帮忙就好了

**Comment by ownself** [comment]
> 我测试了一下，把"cursor_word_highlighter_whole_word"改成false，可以进行选择并用颜色固定高亮，几乎做到StickySearch的功能了，好棒😹！但似乎有个bug，选择中文单字没效果，选择双字及以上都可以正常高亮。而StickySearch对单字也有效。哈，这下选择并颜色固定高亮的问题几乎解决了

哦，我又自己检查了一下代码，原来不能单个单词高亮好像是刻意为之的，我帮你改了一下，你重新下载插件覆盖一下，应该就可以单个字高亮了，cursor_word_highlighter_whole_word我也默认改成false了，如果这个改动引起了其他问题，劳烦再告我一下，因为我有点不记得当初为什么要禁止单个字高亮了

**Comment by tortoo** [comment]
> > 我测试了一下，把"cursor_word_highlighter_whole_word"改成false，可以进行选择并用颜色固定高亮，几乎做到StickySearch的功能了，好棒😹！但似乎有个bug，选择中文单字没效果，选择双字及以上都可以正常高亮。而StickySearch对单字也有效。哈，这下选择并颜色固定高亮的问题几乎解决了
> 
> 哦，我又自己检查了一下代码，原来不能单个单词高亮好像是刻意为之的，我帮你改了一下，你重新下载插件覆盖一下，应该就可以单个字高亮了，cursor_word_highlighter_whole_word我也默认改成false了，如果这个改动引起了其他问题，劳烦再告我一下，因为我有点不记得当初为什么要禁止单个字高凉了

好的，非常感谢！我会一直用的，有啥情况都会报过来，再次感谢哈

**Comment by tortoo** [comment]
抱歉又来打扰，想知道能否取消光标所在单字母的框选，单字固定高亮我看是把这里`if len(word) < 1 `的1改成了2，但它对光标所在单字框选不起作用，通常不太有单字母框选的需求，当文件过大，里面单字母过多的时候，编辑或者放置光标的时候st会卡，估计它会每次都搜索渲染一遍。如果变成双字符及以上才框选，搜索的词频就大大降低了。要是加几句能实现就好了，多谢多谢~ 先祝中秋国庆双节快乐哈！

**Comment by ownself** [comment]
> 抱歉又来打扰，想知道能否取消光标所在单字母的框选，单字固定高亮我看是把这里`if len(word) < 1 `的1改成了2，但它对光标所在单字框选不起作用，通常不太有单字母框选的需求，当文件过大，里面单字母过多的时候，编辑或者放置光标的时候st会卡，估计它会每次都搜索渲染一遍。如果变成双字符及以上才框选，搜索的词频就大大降低了。要是加几句能实现就好了，多谢多谢~ 先祝中秋国庆双节快乐哈！

我可能没有完全理解你的意思，你是说希望不要支持单字的框选吗？插件原本就是不支持单字高亮的，原因一个是需求的情况非常少，第二就是会对性能造成较大影响，所以原本代码里就是"if len(word) < 2"。如果你感觉性能确实有问题的话，改成2应该就好了，等下我会更新下代码仓库的，晚上如果有时间我会把这个做成选项，这样可以更灵活一些

**Comment by tortoo** [comment]
@ownself 我说详细些😹，光标放置后所在词自动框选和alt+enter将框选词或划选词固定高亮是两个功能，1改成2只对后一个固定高亮功能生效，对前一个功能也就是光标放置后自动框选不生效，它还是会自动框选所有单字符

**Comment by tortoo** [comment]
这个是光标放置后自动框选：
![image](https://user-images.githubusercontent.com/28673736/94647506-284ff700-0323-11eb-9d5b-d9ccc8169b49.png)

这个是固定高亮：
![image](https://user-images.githubusercontent.com/28673736/94647594-60573a00-0323-11eb-97b2-142c028dba01.png)

固定高亮需要按下alt+enter生效，所以不会自动触发然后卡顿，但自动框选只要光标放在任意位置，都会自动触发，尤其在编辑状态下，光标是随机移动的。当含有大量相同的单个字符时，光标移到它旁边就会触发全部框选和卡顿

**Comment by ownself** [comment]
> 这个是光标放置后自动框选：
> ![image](https://user-images.githubusercontent.com/28673736/94647506-284ff700-0323-11eb-9d5b-d9ccc8169b49.png)
> 
> 这个是固定高亮：
> ![image](https://user-images.githubusercontent.com/28673736/94647594-60573a00-0323-11eb-97b2-142c028dba01.png)
> 
> 固定高亮需要按下alt+enter生效，所以不会自动触发然后卡顿，但自动框选只要光标放在任意位置，都会自动触发，尤其在编辑状态下，光标是随机移动的。当含有大量相同的单个字符时，光标移到它旁边就会触发全部框选和卡顿

我明白你说的了，这两天我抽时间改进下，不麻烦的应该，多谢宝贵的建议

**Comment by tortoo** [comment]
@ownself 哈，太客气了，应该感谢你，辛苦了！😸

**Comment by tortoo** [comment]
@ownself 好消息😹，我们群里有位厉害的TW小哥，我在群里提了下需求，他动作太快，抢先一步实现了，他把jieba中文分词做成了依赖，然后ChineseTokenizer的作者也用了这个依赖作了更新。中文分词的框选和高亮终于实现了，他也一并做了单字符的处理，做到了选项里。→ [这里](https://github.com/jfcherng-sublime/ST-CursorWordHighlighter)

真的是特别感谢！你们都太厉害了！😻

**Comment by ownself** [comment]
> @ownself 好消息😹，我们群里有位厉害的TW小哥，我在群里提了下需求，他动作太快，抢先一步实现了，他把jieba中文分词做成了依赖，然后ChineseTokenizer的作者也用了这个依赖作了更新。中文分词的框选和高亮终于实现了，他也一并做了单字符的处理，做到了选项里。→ [这里](https://github.com/jfcherng-sublime/ST-CursorWordHighlighter)
> 
> 真的是特别感谢！你们都太厉害了！😻

哇！太棒了，替我谢谢他，有时间我也学习一下他的改动

**Comment by tortoo** [comment]
@ownself 哈，他收到了~ 感谢你们！
